version: "3.8"
services:
  api:
    container_name: reddit_clone
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5050:5050"
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - postgres
      - redis
  mongodb:
    image: mongo:focal
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=reddit-clone
    volumes:
      - mongodb:/data/db
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6380:6379"
    volumes:
      - redis:/etc/redis
  postgres:
    build: docker/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8090:80"
    restart: unless-stopped
    depends_on:
      - postgres
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    restart: unless-stopped
volumes:
  mongodb:
  redis:
  postgres:
  postgres-data:
  pgadmin: