server:
  internalPort: 5005
  externalPort: 5005
  runMode: debug
  requestLimit: 10
logger:
  filePath: logs/
  encoding: json
  level: debug
cors:
  allowOrigins: "*"
mongo:
  host: mongodb_container
  port: 27017
  user: admin
  password: admin
  dbName: reddit-clone
  sslMode: disable
  maxIdleConns: 15
  maxOpenConns: 100
  connMaxLifetime: 5
postgres:
  host: postgres
  port: 5432
  user: admin
  password: admin
  dbName: reddit-clone
  sslMode: disable
  maxIdleConns: 15
  maxOpenConns: 100
  connMaxLifetime: 5
  maxIdleConnsTime: 10
rabbitMq:
  host: rabbitmq_container
  port: 5672
  user: admin
  password: admin
redis:
  host: redis_container
  port: 6379
  password: password
  db: 0
  dialTimeout: 5
  readTimeout: 5
  writeTimeout: 5
  poolSize: 10
  poolTimeout: 15
  idleCheckFrequency: 500
jwt:
  secret: "mySecretKey"
  refreshSecret: "mySecretKey"
  accessTokenExpireDuration: 1440
  refreshTokenExpireDuration: 60
